// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SavingPlatformApplication.Data;

namespace SavingPlatformApplication.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MemberSavingsGroup", b =>
                {
                    b.Property<Guid>("MembersId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SavingsGroupsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MembersId", "SavingsGroupsId");

                    b.HasIndex("SavingsGroupsId");

                    b.ToTable("MemberSavingsGroup");
                });

            modelBuilder.Entity("SavingPlatformApplication.Data.Models.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("StreetName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Town")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("SavingPlatformApplication.Data.Models.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AssetCategory")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<double>("MonetaryValue")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SavingsGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SavingsGroupId1")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SavingsGroupId");

                    b.HasIndex("SavingsGroupId1");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("SavingPlatformApplication.Data.Models.Credit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<double>("FinancialResourceAmount")
                        .HasColumnType("float");

                    b.Property<DateTime>("PaymentPeriod")
                        .HasColumnType("datetime2");

                    b.Property<double>("PercentInterest")
                        .HasColumnType("float");

                    b.Property<Guid>("SavingsGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SavingsGroupId");

                    b.ToTable("Credits");
                });

            modelBuilder.Entity("SavingPlatformApplication.Data.Models.Deposit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SavingsGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SavingsGroupId");

                    b.ToTable("Deposits");
                });

            modelBuilder.Entity("SavingPlatformApplication.Data.Models.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Balance")
                        .HasColumnType("float");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("SavingPlatformApplication.Data.Models.SavingsGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Balance")
                        .HasColumnType("float");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.ToTable("SavingsGroups");
                });

            modelBuilder.Entity("SavingPlatformApplication.Data.Models.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<Guid>("SavingsGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SavingsGroupId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("MemberSavingsGroup", b =>
                {
                    b.HasOne("SavingPlatformApplication.Data.Models.Member", null)
                        .WithMany()
                        .HasForeignKey("MembersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SavingPlatformApplication.Data.Models.SavingsGroup", null)
                        .WithMany()
                        .HasForeignKey("SavingsGroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SavingPlatformApplication.Data.Models.Asset", b =>
                {
                    b.HasOne("SavingPlatformApplication.Data.Models.SavingsGroup", "SavingsGroup")
                        .WithMany("CreatedAssets")
                        .HasForeignKey("SavingsGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SavingPlatformApplication.Data.Models.SavingsGroup", null)
                        .WithMany("PurchasedAssets")
                        .HasForeignKey("SavingsGroupId1");

                    b.Navigation("SavingsGroup");
                });

            modelBuilder.Entity("SavingPlatformApplication.Data.Models.Credit", b =>
                {
                    b.HasOne("SavingPlatformApplication.Data.Models.SavingsGroup", "SavingsGroup")
                        .WithMany("Credits")
                        .HasForeignKey("SavingsGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SavingsGroup");
                });

            modelBuilder.Entity("SavingPlatformApplication.Data.Models.Deposit", b =>
                {
                    b.HasOne("SavingPlatformApplication.Data.Models.SavingsGroup", "SavingsGroup")
                        .WithMany("Deposits")
                        .HasForeignKey("SavingsGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SavingsGroup");
                });

            modelBuilder.Entity("SavingPlatformApplication.Data.Models.Member", b =>
                {
                    b.HasOne("SavingPlatformApplication.Data.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.Navigation("Address");
                });

            modelBuilder.Entity("SavingPlatformApplication.Data.Models.SavingsGroup", b =>
                {
                    b.HasOne("SavingPlatformApplication.Data.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.Navigation("Address");
                });

            modelBuilder.Entity("SavingPlatformApplication.Data.Models.Transaction", b =>
                {
                    b.HasOne("SavingPlatformApplication.Data.Models.SavingsGroup", "SavingsGroup")
                        .WithMany("Transactions")
                        .HasForeignKey("SavingsGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SavingsGroup");
                });

            modelBuilder.Entity("SavingPlatformApplication.Data.Models.SavingsGroup", b =>
                {
                    b.Navigation("CreatedAssets");

                    b.Navigation("Credits");

                    b.Navigation("Deposits");

                    b.Navigation("PurchasedAssets");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
